services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-notif}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-notifpass}
      POSTGRES_DB: ${POSTGRES_DB:-notifications}
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-notif} -d ${POSTGRES_DB:-notifications}"]
      interval: 2s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "56379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 30

  mailhog:
    image: axllent/mailpit:latest
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "1"
      MP_SMTP_AUTH_ALLOW_INSECURE: "1"
    ports:
      - "1025:1025"
      - "8025:8025"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8025/api/v1/info"]
      interval: 5s
      timeout: 3s
      retries: 10

  slack-mock:
    build:
      context: ./mocks/slack
    ports:
      - "9000:9000"

  migrate:
    image: migrate/migrate:v4.17.1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint:
      - sh
      - -c
      - >
        migrate -path=/migrations
        -database "postgres://${POSTGRES_USER:-notif}:${POSTGRES_PASSWORD:-notifpass}@postgres:5432/${POSTGRES_DB:-notifications}?sslmode=disable"
        up
    restart: "no"

  api:
    build:
      context: .
    command: ["api"]
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 3s
      retries: 10

  worker:
    build:
      context: .
    command: ["worker"]
    env_file: .env
    ports:
      - "9101:9100"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  asynqmon:
    image: hibiken/asynqmon:latest
    platform: linux/amd64
    command: ["--redis-addr=redis:6379"]
    ports:
      - "8090:8080"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  pgdata:
  redisdata:
