apiVersion: v1
kind: Secret
metadata:
  name: notifd-env
  namespace: notifd
type: Opaque
stringData:
  API_KEY: "replace-me"
  POSTGRES_USER: "notif"
  POSTGRES_PASSWORD: "replace-me"
  POSTGRES_DB: "notifications"
  POSTGRES_HOST: "db.notifd.svc.cluster.local"
  POSTGRES_PORT: "5432"
  REDIS_ADDR: "redis.notifd.svc.cluster.local:6379"
  SMTP_HOST: "smtp.sendgrid.net"
  SMTP_PORT: "587"
  SMTP_USER: "apikey"
  SMTP_PASSWORD: "replace-me"
  SMTP_FROM: "notifications@example.com"
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/REPLACE"
